load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "SDL2",
    remote = "https://github.com/nikan1234/bazelSDL2_fullpack/",
    commit = "9c66817c4140cbf68bcc60b9fbb6dcb66bfb615e",
)

git_repository(
    name = "Box2D",
    remote = "https://github.com/nikan1234/box2d_bazel",
    commit = "625ef19e8234ac87afb056d8d00678836ce0fd74",
)
