cc_library(
    name = "circular_buffer",
    hdrs = ["circular_buffer.h"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        ":circular_buffer",
    ]
)